on:
  push:
    branches: [main]
  pull_request:

# Apparently splitting these into separate jobs is not really a thing on GitHub. All the
# examples here use a single job:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

jobs:
  build_lint_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - run: poetry install
    - run: poetry run pre-commit run -a
    - run: poetry run pytest
